language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
before_install:
 - which $CC
 - export CC=`which $CC`
 - sudo apt-get update -qq
 - sudo apt-get install -qq gtk-doc-tools libgnutls-dev libgsasl7-dev libxml2-dev libglib2.0-dev libgtk-3-dev libavahi-client-dev libdaemon-dev libpam-dev gobject-introspection libexpat1-dev zlib1g-dev
 - wget https://github.com/gobby/libinfinity/archive/master.tar.gz -O /tmp/infinote-master.tar.gz
 - tar -xzf /tmp/infinote-master.tar.gz
 - cd libinfinity-master && ./autogen.sh --with-gtk3 --with-infgtk --with-inftextgtk --with-avahi --with-libdaemon --disable-gtk-doc && make -j3 && sudo -E make install && cd ..
install:
 - sudo apt-get install -qq libxml++2.6-dev libglibmm-2.4-dev libgtkmm-3.0-dev libgtksourceview-3.0-dev libgsasl7-dev libunique-3.0-dev gettext intltool gnome-doc-utils rarian-compat
script: ./autogen.sh && ./configure --with-unique --with-gtk3 && make -j3
